/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI
 */
public class DosenMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public DosenMenu() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JenisKelamin = new javax.swing.ButtonGroup();
        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBuatKelasTA = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnUbahKelasTA = new javax.swing.JButton();
        btnLihatKelasTA = new javax.swing.JButton();
        btnKonfirmasi = new javax.swing.JButton();
        btnUbahPassword = new javax.swing.JButton();
        DosenParentPanel = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextNamaDosen = new javax.swing.JLabel();
        TextNIDDosen = new javax.swing.JLabel();
        BuatKelasTA = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfTopikBuatTA = new javax.swing.JTextField();
        btnBuatKelas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListKelasBuatTA = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane24 = new javax.swing.JScrollPane();
        TabelDosenBuatKelas = new javax.swing.JTable();
        jScrollPane25 = new javax.swing.JScrollPane();
        TabelMhsBuatKelas = new javax.swing.JTable();
        UbahTAParent = new javax.swing.JPanel();
        UbahTAHome = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnTambahDosenUbahTA = new javax.swing.JButton();
        btnHapusDosenUbahTA = new javax.swing.JButton();
        btnHapusMahasiswaUbahTA = new javax.swing.JButton();
        btnHapusKelasTA = new javax.swing.JButton();
        UbahTATambahDosen = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnTambahDosen = new javax.swing.JButton();
        btnKembaliTambahDosen = new javax.swing.JButton();
        jScrollPane21 = new javax.swing.JScrollPane();
        TabelTambahDosen = new javax.swing.JTable();
        UbahTAHapusDosen = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnHapusDosen = new javax.swing.JButton();
        btnKembaliHapusDosen = new javax.swing.JButton();
        jScrollPane20 = new javax.swing.JScrollPane();
        TabelHapusDosen = new javax.swing.JTable();
        UbahTAHapusMhs = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnHapusMhs = new javax.swing.JButton();
        btnKembaliHapusMhs = new javax.swing.JButton();
        jScrollPane19 = new javax.swing.JScrollPane();
        TabelHapusMhs = new javax.swing.JTable();
        LihatKelasTAParent = new javax.swing.JPanel();
        LihatKelasTAHome = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnLihatKelasIkut = new javax.swing.JButton();
        btnLihatKelasAnda = new javax.swing.JButton();
        KelasTAAnda = new javax.swing.JPanel();
        btnKembaliKelasAnda = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        TabelMhsKelasAnda = new javax.swing.JTable();
        jScrollPane23 = new javax.swing.JScrollPane();
        TabelDosenKelasAnda = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        KelasYangDiikuti = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        ListIkutLihatKelas = new javax.swing.JList<>();
        btnKembaliIkutLihatKelas = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane27 = new javax.swing.JScrollPane();
        TabelDosenIkut = new javax.swing.JTable();
        jScrollPane28 = new javax.swing.JScrollPane();
        TabelMhsIkut = new javax.swing.JTable();
        Konfirmasi = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        btnTerimaKonfirmasi = new javax.swing.JButton();
        btnTolakKonfirmasi = new javax.swing.JButton();
        jScrollPane26 = new javax.swing.JScrollPane();
        TabelKonfirmasi = new javax.swing.JTable();
        UbahPassword = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tfPasswordLama = new javax.swing.JPasswordField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tfPasswordBaru = new javax.swing.JPasswordField();
        tfKonfirmPassword = new javax.swing.JPasswordField();
        btnUbahPass = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");
        popupMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupMenu1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEM INFORMASI DATA TUGAS AKHIR");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MiniLogo.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btnBuatKelasTA.setBackground(new java.awt.Color(51, 0, 0));
        btnBuatKelasTA.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btnBuatKelasTA.setForeground(new java.awt.Color(255, 255, 255));
        btnBuatKelasTA.setText("Buat Kelas TA");
        btnBuatKelasTA.setFocusPainted(false);
        btnBuatKelasTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatKelasTAActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(51, 0, 0));
        btnLogOut.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Keluar");
        btnLogOut.setFocusPainted(false);

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DOSEN");

        btnUbahKelasTA.setBackground(new java.awt.Color(51, 0, 0));
        btnUbahKelasTA.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btnUbahKelasTA.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahKelasTA.setText("Ubah Kelas TA");
        btnUbahKelasTA.setFocusPainted(false);
        btnUbahKelasTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahKelasTAActionPerformed(evt);
            }
        });

        btnLihatKelasTA.setBackground(new java.awt.Color(51, 0, 0));
        btnLihatKelasTA.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btnLihatKelasTA.setForeground(new java.awt.Color(255, 255, 255));
        btnLihatKelasTA.setText("Lihat Kelas TA");
        btnLihatKelasTA.setFocusPainted(false);
        btnLihatKelasTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatKelasTAActionPerformed(evt);
            }
        });

        btnKonfirmasi.setBackground(new java.awt.Color(51, 0, 0));
        btnKonfirmasi.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        btnKonfirmasi.setForeground(new java.awt.Color(255, 255, 255));
        btnKonfirmasi.setText("Konfirmasi Pembimbing");
        btnKonfirmasi.setFocusPainted(false);
        btnKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiActionPerformed(evt);
            }
        });

        btnUbahPassword.setBackground(new java.awt.Color(51, 0, 0));
        btnUbahPassword.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btnUbahPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahPassword.setText("Ubah Password");
        btnUbahPassword.setFocusPainted(false);
        btnUbahPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuatKelasTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUbahKelasTA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLihatKelasTA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKonfirmasi, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(btnUbahPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuatKelasTA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnUbahKelasTA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnLihatKelasTA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnUbahPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        DosenParentPanel.setBackground(new java.awt.Color(153, 153, 153));
        DosenParentPanel.setLayout(new java.awt.CardLayout());

        Home.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/LogoTelkom.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SELAMAT DATANG");

        TextNamaDosen.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        TextNamaDosen.setForeground(new java.awt.Color(255, 255, 255));
        TextNamaDosen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        TextNIDDosen.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        TextNIDDosen.setForeground(new java.awt.Color(255, 255, 255));
        TextNIDDosen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextNIDDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(TextNIDDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );

        DosenParentPanel.add(Home, "card5");

        BuatKelasTA.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Topik");

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BUAT KELAS TUGAS AKHIR");

        tfTopikBuatTA.setEditable(false);
        tfTopikBuatTA.setBackground(new java.awt.Color(51, 51, 51));
        tfTopikBuatTA.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        tfTopikBuatTA.setForeground(new java.awt.Color(255, 255, 255));

        btnBuatKelas.setBackground(new java.awt.Color(0, 51, 0));
        btnBuatKelas.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnBuatKelas.setForeground(new java.awt.Color(255, 255, 255));
        btnBuatKelas.setText("Buat Kelas TA");
        btnBuatKelas.setFocusPainted(false);

        ListKelasBuatTA.setBackground(new java.awt.Color(204, 204, 204));
        ListKelasBuatTA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(ListKelasBuatTA);

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Daftar Kelas TA");

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Dosen");

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Mahasiswa");

        TabelDosenBuatKelas.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        TabelDosenBuatKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NID", "Nama"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane24.setViewportView(TabelDosenBuatKelas);

        TabelMhsBuatKelas.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        TabelMhsBuatKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane25.setViewportView(TabelMhsBuatKelas);

        javax.swing.GroupLayout BuatKelasTALayout = new javax.swing.GroupLayout(BuatKelasTA);
        BuatKelasTA.setLayout(BuatKelasTALayout);
        BuatKelasTALayout.setHorizontalGroup(
            BuatKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuatKelasTALayout.createSequentialGroup()
                .addGroup(BuatKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuatKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(BuatKelasTALayout.createSequentialGroup()
                            .addGroup(BuatKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(BuatKelasTALayout.createSequentialGroup()
                                    .addGap(102, 102, 102)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(BuatKelasTALayout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(61, 61, 61))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BuatKelasTALayout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BuatKelasTALayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(BuatKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnBuatKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfTopikBuatTA, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(BuatKelasTALayout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(170, 170, 170))
                                .addGroup(BuatKelasTALayout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(88, 88, 88)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(72, 72, 72)))))
                    .addGroup(BuatKelasTALayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        BuatKelasTALayout.setVerticalGroup(
            BuatKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuatKelasTALayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(BuatKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTopikBuatTA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnBuatKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BuatKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BuatKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane24, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(126, 126, 126))
        );

        DosenParentPanel.add(BuatKelasTA, "card3");

        UbahTAParent.setBackground(new java.awt.Color(153, 153, 153));
        UbahTAParent.setLayout(new java.awt.CardLayout());

        UbahTAHome.setBackground(new java.awt.Color(102, 102, 102));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("UBAH KELAS TA");

        btnTambahDosenUbahTA.setBackground(new java.awt.Color(51, 0, 0));
        btnTambahDosenUbahTA.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnTambahDosenUbahTA.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahDosenUbahTA.setText("Tambah Dosen");
        btnTambahDosenUbahTA.setFocusPainted(false);
        btnTambahDosenUbahTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDosenUbahTAActionPerformed(evt);
            }
        });

        btnHapusDosenUbahTA.setBackground(new java.awt.Color(51, 0, 0));
        btnHapusDosenUbahTA.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnHapusDosenUbahTA.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusDosenUbahTA.setText("Hapus Dosen");
        btnHapusDosenUbahTA.setFocusPainted(false);
        btnHapusDosenUbahTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusDosenUbahTAActionPerformed(evt);
            }
        });

        btnHapusMahasiswaUbahTA.setBackground(new java.awt.Color(51, 0, 0));
        btnHapusMahasiswaUbahTA.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnHapusMahasiswaUbahTA.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusMahasiswaUbahTA.setText("Hapus Mahasiswa");
        btnHapusMahasiswaUbahTA.setFocusPainted(false);
        btnHapusMahasiswaUbahTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusMahasiswaUbahTAActionPerformed(evt);
            }
        });

        btnHapusKelasTA.setBackground(new java.awt.Color(51, 0, 0));
        btnHapusKelasTA.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnHapusKelasTA.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusKelasTA.setText("Hapus Kelas TA");
        btnHapusKelasTA.setFocusPainted(false);

        javax.swing.GroupLayout UbahTAHomeLayout = new javax.swing.GroupLayout(UbahTAHome);
        UbahTAHome.setLayout(UbahTAHomeLayout);
        UbahTAHomeLayout.setHorizontalGroup(
            UbahTAHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UbahTAHomeLayout.createSequentialGroup()
                .addGroup(UbahTAHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UbahTAHomeLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(UbahTAHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHapusDosenUbahTA, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapusMahasiswaUbahTA, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambahDosenUbahTA, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapusKelasTA, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(UbahTAHomeLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        UbahTAHomeLayout.setVerticalGroup(
            UbahTAHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UbahTAHomeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnTambahDosenUbahTA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapusDosenUbahTA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapusMahasiswaUbahTA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btnHapusKelasTA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        UbahTAParent.add(UbahTAHome, "card2");

        UbahTATambahDosen.setBackground(new java.awt.Color(102, 102, 102));

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TAMBAH DOSEN KELAS TA");

        btnTambahDosen.setBackground(new java.awt.Color(0, 51, 0));
        btnTambahDosen.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnTambahDosen.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahDosen.setText("Tambah");

        btnKembaliTambahDosen.setBackground(new java.awt.Color(51, 0, 0));
        btnKembaliTambahDosen.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnKembaliTambahDosen.setForeground(new java.awt.Color(255, 255, 255));
        btnKembaliTambahDosen.setText("Kembali");
        btnKembaliTambahDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliTambahDosenActionPerformed(evt);
            }
        });

        TabelTambahDosen.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        TabelTambahDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NID", "Nama", "Kode Dosen", "Gender", "Topik", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane21.setViewportView(TabelTambahDosen);

        javax.swing.GroupLayout UbahTATambahDosenLayout = new javax.swing.GroupLayout(UbahTATambahDosen);
        UbahTATambahDosen.setLayout(UbahTATambahDosenLayout);
        UbahTATambahDosenLayout.setHorizontalGroup(
            UbahTATambahDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UbahTATambahDosenLayout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addGroup(UbahTATambahDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UbahTATambahDosenLayout.createSequentialGroup()
                        .addGroup(UbahTATambahDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKembaliTambahDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UbahTATambahDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnTambahDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UbahTATambahDosenLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );
        UbahTATambahDosenLayout.setVerticalGroup(
            UbahTATambahDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UbahTATambahDosenLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTambahDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(btnKembaliTambahDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        UbahTAParent.add(UbahTATambahDosen, "card3");

        UbahTAHapusDosen.setBackground(new java.awt.Color(102, 102, 102));

        jLabel16.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("HAPUS DOSEN KELAS TA");

        btnHapusDosen.setBackground(new java.awt.Color(0, 51, 0));
        btnHapusDosen.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnHapusDosen.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusDosen.setText("Hapus");
        btnHapusDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusDosenActionPerformed(evt);
            }
        });

        btnKembaliHapusDosen.setBackground(new java.awt.Color(51, 0, 0));
        btnKembaliHapusDosen.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnKembaliHapusDosen.setForeground(new java.awt.Color(255, 255, 255));
        btnKembaliHapusDosen.setText("Kembali");
        btnKembaliHapusDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliHapusDosenActionPerformed(evt);
            }
        });

        TabelHapusDosen.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        TabelHapusDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Kode Dosen", "Gender", "Topik", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane20.setViewportView(TabelHapusDosen);

        javax.swing.GroupLayout UbahTAHapusDosenLayout = new javax.swing.GroupLayout(UbahTAHapusDosen);
        UbahTAHapusDosen.setLayout(UbahTAHapusDosenLayout);
        UbahTAHapusDosenLayout.setHorizontalGroup(
            UbahTAHapusDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UbahTAHapusDosenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UbahTAHapusDosenLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(UbahTAHapusDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembaliHapusDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UbahTAHapusDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnHapusDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        UbahTAHapusDosenLayout.setVerticalGroup(
            UbahTAHapusDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UbahTAHapusDosenLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnHapusDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(btnKembaliHapusDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        UbahTAParent.add(UbahTAHapusDosen, "card3");

        UbahTAHapusMhs.setBackground(new java.awt.Color(102, 102, 102));

        jLabel19.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("HAPUS MAHASISWA KELAS TA");

        btnHapusMhs.setBackground(new java.awt.Color(0, 51, 0));
        btnHapusMhs.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnHapusMhs.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusMhs.setText("Hapus");
        btnHapusMhs.setFocusPainted(false);
        btnHapusMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusMhsActionPerformed(evt);
            }
        });

        btnKembaliHapusMhs.setBackground(new java.awt.Color(51, 0, 0));
        btnKembaliHapusMhs.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnKembaliHapusMhs.setForeground(new java.awt.Color(255, 255, 255));
        btnKembaliHapusMhs.setText("Kembali");
        btnKembaliHapusMhs.setFocusPainted(false);
        btnKembaliHapusMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliHapusMhsActionPerformed(evt);
            }
        });

        TabelHapusMhs.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        TabelHapusMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Gender", "Email", "Judul TA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane19.setViewportView(TabelHapusMhs);

        javax.swing.GroupLayout UbahTAHapusMhsLayout = new javax.swing.GroupLayout(UbahTAHapusMhs);
        UbahTAHapusMhs.setLayout(UbahTAHapusMhsLayout);
        UbahTAHapusMhsLayout.setHorizontalGroup(
            UbahTAHapusMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UbahTAHapusMhsLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(UbahTAHapusMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UbahTAHapusMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnKembaliHapusMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        UbahTAHapusMhsLayout.setVerticalGroup(
            UbahTAHapusMhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UbahTAHapusMhsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapusMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(btnKembaliHapusMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        UbahTAParent.add(UbahTAHapusMhs, "card3");

        DosenParentPanel.add(UbahTAParent, "card4");

        LihatKelasTAParent.setBackground(new java.awt.Color(102, 102, 102));
        LihatKelasTAParent.setLayout(new java.awt.CardLayout());

        LihatKelasTAHome.setBackground(new java.awt.Color(102, 102, 102));

        jLabel13.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("LIHAT KELAS TA");

        btnLihatKelasIkut.setBackground(new java.awt.Color(51, 0, 0));
        btnLihatKelasIkut.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnLihatKelasIkut.setForeground(new java.awt.Color(255, 255, 255));
        btnLihatKelasIkut.setText("Kelas TA yang Diikuti");
        btnLihatKelasIkut.setFocusPainted(false);
        btnLihatKelasIkut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatKelasIkutActionPerformed(evt);
            }
        });

        btnLihatKelasAnda.setBackground(new java.awt.Color(51, 0, 0));
        btnLihatKelasAnda.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnLihatKelasAnda.setForeground(new java.awt.Color(255, 255, 255));
        btnLihatKelasAnda.setText("Kelas TA Anda");
        btnLihatKelasAnda.setFocusPainted(false);
        btnLihatKelasAnda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatKelasAndaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LihatKelasTAHomeLayout = new javax.swing.GroupLayout(LihatKelasTAHome);
        LihatKelasTAHome.setLayout(LihatKelasTAHomeLayout);
        LihatKelasTAHomeLayout.setHorizontalGroup(
            LihatKelasTAHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LihatKelasTAHomeLayout.createSequentialGroup()
                .addGroup(LihatKelasTAHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LihatKelasTAHomeLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LihatKelasTAHomeLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(LihatKelasTAHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLihatKelasAnda, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLihatKelasIkut, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        LihatKelasTAHomeLayout.setVerticalGroup(
            LihatKelasTAHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LihatKelasTAHomeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnLihatKelasAnda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnLihatKelasIkut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        LihatKelasTAParent.add(LihatKelasTAHome, "card2");

        KelasTAAnda.setBackground(new java.awt.Color(102, 102, 102));

        btnKembaliKelasAnda.setBackground(new java.awt.Color(51, 0, 0));
        btnKembaliKelasAnda.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnKembaliKelasAnda.setForeground(new java.awt.Color(255, 255, 255));
        btnKembaliKelasAnda.setText("Kembali");
        btnKembaliKelasAnda.setFocusPainted(false);
        btnKembaliKelasAnda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliKelasAndaActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("KELAS TA ANDA");

        jLabel24.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Daftar Mahasiswa");

        TabelMhsKelasAnda.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        TabelMhsKelasAnda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Gender", "Email", "Judul TA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane22.setViewportView(TabelMhsKelasAnda);

        TabelDosenKelasAnda.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        TabelDosenKelasAnda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Kode Dosen", "Gender", "Topik", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane23.setViewportView(TabelDosenKelasAnda);

        jLabel33.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Daftar Dosen");

        javax.swing.GroupLayout KelasTAAndaLayout = new javax.swing.GroupLayout(KelasTAAnda);
        KelasTAAnda.setLayout(KelasTAAndaLayout);
        KelasTAAndaLayout.setHorizontalGroup(
            KelasTAAndaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KelasTAAndaLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(KelasTAAndaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KelasTAAndaLayout.createSequentialGroup()
                        .addGroup(KelasTAAndaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKembaliKelasAnda, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KelasTAAndaLayout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KelasTAAndaLayout.createSequentialGroup()
                        .addGroup(KelasTAAndaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(152, 152, 152))))
        );
        KelasTAAndaLayout.setVerticalGroup(
            KelasTAAndaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KelasTAAndaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnKembaliKelasAnda, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        LihatKelasTAParent.add(KelasTAAnda, "card3");

        KelasYangDiikuti.setBackground(new java.awt.Color(102, 102, 102));

        jLabel25.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("KELAS YANG DIIKUTI");

        ListIkutLihatKelas.setBackground(new java.awt.Color(204, 204, 204));
        ListIkutLihatKelas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane10.setViewportView(ListIkutLihatKelas);

        btnKembaliIkutLihatKelas.setBackground(new java.awt.Color(51, 0, 0));
        btnKembaliIkutLihatKelas.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnKembaliIkutLihatKelas.setForeground(new java.awt.Color(255, 255, 255));
        btnKembaliIkutLihatKelas.setText("Kembali");
        btnKembaliIkutLihatKelas.setFocusPainted(false);
        btnKembaliIkutLihatKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliIkutLihatKelasActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Dosen");

        jLabel27.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Mahasiswa");

        TabelDosenIkut.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        TabelDosenIkut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NID", "Nama"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane27.setViewportView(TabelDosenIkut);

        TabelMhsIkut.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        TabelMhsIkut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane28.setViewportView(TabelMhsIkut);

        javax.swing.GroupLayout KelasYangDiikutiLayout = new javax.swing.GroupLayout(KelasYangDiikuti);
        KelasYangDiikuti.setLayout(KelasYangDiikutiLayout);
        KelasYangDiikutiLayout.setHorizontalGroup(
            KelasYangDiikutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KelasYangDiikutiLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(KelasYangDiikutiLayout.createSequentialGroup()
                .addGroup(KelasYangDiikutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KelasYangDiikutiLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(KelasYangDiikutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKembaliIkutLihatKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KelasYangDiikutiLayout.createSequentialGroup()
                                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(KelasYangDiikutiLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(KelasYangDiikutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        KelasYangDiikutiLayout.setVerticalGroup(
            KelasYangDiikutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KelasYangDiikutiLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(KelasYangDiikutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KelasYangDiikutiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane28, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(102, 102, 102)
                .addComponent(btnKembaliIkutLihatKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        LihatKelasTAParent.add(KelasYangDiikuti, "card4");

        DosenParentPanel.add(LihatKelasTAParent, "card5");

        Konfirmasi.setBackground(new java.awt.Color(102, 102, 102));

        jLabel28.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("KONFIRMASI PEMBIMBING");

        btnTerimaKonfirmasi.setBackground(new java.awt.Color(0, 51, 0));
        btnTerimaKonfirmasi.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnTerimaKonfirmasi.setForeground(new java.awt.Color(255, 255, 255));
        btnTerimaKonfirmasi.setText("Terima");
        btnTerimaKonfirmasi.setFocusPainted(false);

        btnTolakKonfirmasi.setBackground(new java.awt.Color(51, 0, 0));
        btnTolakKonfirmasi.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnTolakKonfirmasi.setForeground(new java.awt.Color(255, 255, 255));
        btnTolakKonfirmasi.setText("Tolak");
        btnTolakKonfirmasi.setFocusPainted(false);

        TabelKonfirmasi.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        TabelKonfirmasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Gender", "Email", "Judul TA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane26.setViewportView(TabelKonfirmasi);

        javax.swing.GroupLayout KonfirmasiLayout = new javax.swing.GroupLayout(Konfirmasi);
        Konfirmasi.setLayout(KonfirmasiLayout);
        KonfirmasiLayout.setHorizontalGroup(
            KonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KonfirmasiLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KonfirmasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(KonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(KonfirmasiLayout.createSequentialGroup()
                        .addComponent(btnTolakKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTerimaKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        KonfirmasiLayout.setVerticalGroup(
            KonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KonfirmasiLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(KonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTerimaKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTolakKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(288, Short.MAX_VALUE))
        );

        DosenParentPanel.add(Konfirmasi, "card6");

        UbahPassword.setBackground(new java.awt.Color(102, 102, 102));

        jLabel29.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("UBAH PASSWORD");

        jLabel30.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Password Lama");

        tfPasswordLama.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Password Baru");

        jLabel32.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Konfirmasi Password");

        tfPasswordBaru.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        tfKonfirmPassword.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        btnUbahPass.setBackground(new java.awt.Color(0, 51, 0));
        btnUbahPass.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnUbahPass.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahPass.setText("Ubah Password");
        btnUbahPass.setFocusPainted(false);
        btnUbahPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UbahPasswordLayout = new javax.swing.GroupLayout(UbahPassword);
        UbahPassword.setLayout(UbahPasswordLayout);
        UbahPasswordLayout.setHorizontalGroup(
            UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UbahPasswordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(UbahPasswordLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUbahPass, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UbahPasswordLayout.createSequentialGroup()
                        .addGroup(UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPasswordLama, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPasswordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfKonfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        UbahPasswordLayout.setVerticalGroup(
            UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UbahPasswordLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(tfPasswordLama))
                .addGap(34, 34, 34)
                .addGroup(UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfPasswordBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UbahPasswordLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addGroup(UbahPasswordLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfKonfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(btnUbahPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );

        DosenParentPanel.add(UbahPassword, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(DosenParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DosenParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuatKelasTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatKelasTAActionPerformed
        DosenParentPanel.removeAll();
        DosenParentPanel.add(BuatKelasTA);
        DosenParentPanel.repaint();
        DosenParentPanel.revalidate();
    }//GEN-LAST:event_btnBuatKelasTAActionPerformed

    private void btnUbahKelasTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahKelasTAActionPerformed
        DosenParentPanel.removeAll();
        DosenParentPanel.add(UbahTAParent);
        DosenParentPanel.repaint();
        DosenParentPanel.revalidate();
        UbahTAParent.removeAll();
        UbahTAParent.add(UbahTAHome);
        UbahTAParent.repaint();
        UbahTAParent.revalidate();
    }//GEN-LAST:event_btnUbahKelasTAActionPerformed

    private void btnLihatKelasTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatKelasTAActionPerformed
        DosenParentPanel.removeAll();
        DosenParentPanel.add(LihatKelasTAParent);
        DosenParentPanel.repaint();
        DosenParentPanel.revalidate();
        LihatKelasTAParent.removeAll();
        LihatKelasTAParent.add(LihatKelasTAHome);
        LihatKelasTAParent.repaint();
        LihatKelasTAParent.revalidate();
    }//GEN-LAST:event_btnLihatKelasTAActionPerformed

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed
        DosenParentPanel.removeAll();
        DosenParentPanel.add(Konfirmasi);
        DosenParentPanel.repaint();
        DosenParentPanel.revalidate();
    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    private void btnUbahPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahPasswordActionPerformed
        DosenParentPanel.removeAll();
        DosenParentPanel.add(UbahPassword);
        DosenParentPanel.repaint();
        DosenParentPanel.revalidate();
    }//GEN-LAST:event_btnUbahPasswordActionPerformed

    private void btnTambahDosenUbahTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDosenUbahTAActionPerformed
        UbahTAParent.removeAll();
        UbahTAParent.add(UbahTATambahDosen);
        UbahTAParent.repaint();
        UbahTAParent.revalidate();
    }//GEN-LAST:event_btnTambahDosenUbahTAActionPerformed

    private void btnKembaliKelasAndaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliKelasAndaActionPerformed
        LihatKelasTAParent.removeAll();
        LihatKelasTAParent.add(LihatKelasTAHome);
        LihatKelasTAParent.repaint();
        LihatKelasTAParent.revalidate();
    }//GEN-LAST:event_btnKembaliKelasAndaActionPerformed

    private void btnKembaliIkutLihatKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliIkutLihatKelasActionPerformed
        LihatKelasTAParent.removeAll();
        LihatKelasTAParent.add(LihatKelasTAHome);
        LihatKelasTAParent.repaint();
        LihatKelasTAParent.revalidate();
    }//GEN-LAST:event_btnKembaliIkutLihatKelasActionPerformed

    private void btnLihatKelasAndaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatKelasAndaActionPerformed
        LihatKelasTAParent.removeAll();
        LihatKelasTAParent.add(KelasTAAnda);
        LihatKelasTAParent.repaint();
        LihatKelasTAParent.revalidate();
    }//GEN-LAST:event_btnLihatKelasAndaActionPerformed

    private void btnLihatKelasIkutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatKelasIkutActionPerformed
        LihatKelasTAParent.removeAll();
        LihatKelasTAParent.add(KelasYangDiikuti);
        LihatKelasTAParent.repaint();
        LihatKelasTAParent.revalidate();
    }//GEN-LAST:event_btnLihatKelasIkutActionPerformed

    private void btnHapusDosenUbahTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDosenUbahTAActionPerformed
        UbahTAParent.removeAll();
        UbahTAParent.add(UbahTAHapusDosen);
        UbahTAParent.repaint();
        UbahTAParent.revalidate();
    }//GEN-LAST:event_btnHapusDosenUbahTAActionPerformed

    private void btnHapusMahasiswaUbahTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusMahasiswaUbahTAActionPerformed
        UbahTAParent.removeAll();
        UbahTAParent.add(UbahTAHapusMhs);
        UbahTAParent.repaint();
        UbahTAParent.revalidate();
    }//GEN-LAST:event_btnHapusMahasiswaUbahTAActionPerformed

    private void btnKembaliHapusMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliHapusMhsActionPerformed
        UbahTAParent.removeAll();
        UbahTAParent.add(UbahTAHome);
        UbahTAParent.repaint();
        UbahTAParent.revalidate();
    }//GEN-LAST:event_btnKembaliHapusMhsActionPerformed

    private void btnKembaliHapusDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliHapusDosenActionPerformed
        UbahTAParent.removeAll();
        UbahTAParent.add(UbahTAHome);
        UbahTAParent.repaint();
        UbahTAParent.revalidate();
    }//GEN-LAST:event_btnKembaliHapusDosenActionPerformed

    private void btnKembaliTambahDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliTambahDosenActionPerformed
        UbahTAParent.removeAll();
        UbahTAParent.add(UbahTAHome);
        UbahTAParent.repaint();
        UbahTAParent.revalidate();
    }//GEN-LAST:event_btnKembaliTambahDosenActionPerformed

    private void btnHapusMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusMhsActionPerformed

    }//GEN-LAST:event_btnHapusMhsActionPerformed

    private void btnUbahPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahPassActionPerformed

    private void popupMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popupMenu1ActionPerformed

    private void btnHapusDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusDosenActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuatKelasTA;
    private javax.swing.JPanel DosenParentPanel;
    private javax.swing.JPanel Home;
    private javax.swing.ButtonGroup JenisKelamin;
    private javax.swing.JPanel KelasTAAnda;
    private javax.swing.JPanel KelasYangDiikuti;
    private javax.swing.JPanel Konfirmasi;
    private javax.swing.JPanel LihatKelasTAHome;
    private javax.swing.JPanel LihatKelasTAParent;
    private javax.swing.JList<String> ListIkutLihatKelas;
    private javax.swing.JList<String> ListKelasBuatTA;
    private javax.swing.JTable TabelDosenBuatKelas;
    private javax.swing.JTable TabelDosenIkut;
    private javax.swing.JTable TabelDosenKelasAnda;
    private javax.swing.JTable TabelHapusDosen;
    private javax.swing.JTable TabelHapusMhs;
    private javax.swing.JTable TabelKonfirmasi;
    private javax.swing.JTable TabelMhsBuatKelas;
    private javax.swing.JTable TabelMhsIkut;
    private javax.swing.JTable TabelMhsKelasAnda;
    private javax.swing.JTable TabelTambahDosen;
    private javax.swing.JLabel TextNIDDosen;
    private javax.swing.JLabel TextNamaDosen;
    private javax.swing.JPanel UbahPassword;
    private javax.swing.JPanel UbahTAHapusDosen;
    private javax.swing.JPanel UbahTAHapusMhs;
    private javax.swing.JPanel UbahTAHome;
    private javax.swing.JPanel UbahTAParent;
    private javax.swing.JPanel UbahTATambahDosen;
    private javax.swing.JButton btnBuatKelas;
    private javax.swing.JButton btnBuatKelasTA;
    private javax.swing.JButton btnHapusDosen;
    private javax.swing.JButton btnHapusDosenUbahTA;
    private javax.swing.JButton btnHapusKelasTA;
    private javax.swing.JButton btnHapusMahasiswaUbahTA;
    private javax.swing.JButton btnHapusMhs;
    private javax.swing.JButton btnKembaliHapusDosen;
    private javax.swing.JButton btnKembaliHapusMhs;
    private javax.swing.JButton btnKembaliIkutLihatKelas;
    private javax.swing.JButton btnKembaliKelasAnda;
    private javax.swing.JButton btnKembaliTambahDosen;
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JButton btnLihatKelasAnda;
    private javax.swing.JButton btnLihatKelasIkut;
    private javax.swing.JButton btnLihatKelasTA;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnTambahDosen;
    private javax.swing.JButton btnTambahDosenUbahTA;
    private javax.swing.JButton btnTerimaKonfirmasi;
    private javax.swing.JButton btnTolakKonfirmasi;
    private javax.swing.JButton btnUbahKelasTA;
    private javax.swing.JButton btnUbahPass;
    private javax.swing.JButton btnUbahPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JPasswordField tfKonfirmPassword;
    private javax.swing.JPasswordField tfPasswordBaru;
    private javax.swing.JPasswordField tfPasswordLama;
    private javax.swing.JTextField tfTopikBuatTA;
    // End of variables declaration//GEN-END:variables

    //Buat Kelas TA
    public JList getListKelasBuatKelas(){
        return ListKelasBuatTA;
    }
    
    public int getIndexListBuatKelas(){
        return ListKelasBuatTA.getSelectedIndex();
    }
    
    public void setListBuatTA(String[] s){
        ListKelasBuatTA.setListData(s);
    }
    
    public void setTabelMhsBuatKelas(String NIM, String Nama){
        DefaultTableModel model = (DefaultTableModel) TabelMhsBuatKelas.getModel();
        model.addRow(new Object[]{NIM, Nama});
    }
    
    public void setTabelDosenBuatKelas(String NID, String Nama){
        DefaultTableModel model = (DefaultTableModel) TabelDosenBuatKelas.getModel();
        model.addRow(new Object[]{NID, Nama});

    }
    
    public void setTopikKelasTA(String Topik){
        tfTopikBuatTA.setText(Topik);
    }
    
    public JButton getbtnBuatKelas(){
        return btnBuatKelas;
    }
    //End of Buat Kelas TA
    
    //Tambah Dosen Kelas TA
    public JButton getbtnTambahDosen(){
        return btnTambahDosen;
    }
    
    public int getIndexTambahDosen(){
        return TabelTambahDosen.getSelectedRow();
    }
    
    public void setTabelTambahDosen(String NID, String Nama, String Kode, String Gender, String Topik, String Email){
        DefaultTableModel model = (DefaultTableModel) TabelTambahDosen.getModel();
        model.addRow(new Object[]{NID, Nama, Kode, Gender, Topik, Email});
    }
    //End of Tambah Dosen Kelas TA
    
    //Hapus Dosen Kelas TA
    public JButton getbtnHapusDosen(){
        return btnHapusDosen;
    }
    
    public int getIndexHapusDosen(){
        return TabelHapusDosen.getSelectedRow();
    }
    
    public void setTabelHapusDosen(String NID, String Nama, String Kode, String Gender, String Topik, String Email){
        DefaultTableModel model = (DefaultTableModel) TabelHapusDosen.getModel();
        model.addRow(new Object[]{NID, Nama, Kode, Gender, Topik, Email});
    }
    //End of Hapus Dosen Kelas TA
    
    //Hapus Mahasiswa Kelas TA
    public JButton getbtnHapusMhs(){
        return btnHapusMhs;
    }
    
    public int getIndexHapusMhs(){
        return TabelHapusMhs.getSelectedRow();
    }
    
    public void setTabelHapusMhs(String NIM, String Nama, String Gender, String Email, String Topik){
        DefaultTableModel model = (DefaultTableModel) TabelHapusMhs.getModel();
        model.addRow(new Object[]{NIM, Nama, Gender, Email, Topik});
    }
    //End of Hapus Mahasiswa Kelas TA
    
    //Lihat Kelas
    public void setTabelMhsKelasAnda(String NIM, String Nama, String Gender, String Email, String Topik){
        DefaultTableModel model = (DefaultTableModel) TabelMhsKelasAnda.getModel();
        model.addRow(new Object[]{NIM, Nama, Gender, Email, Topik});
    }
    
    public void setTabelDosenKelasAnda(String NID, String Nama, String Kode, String Gender, String Topik, String Email){
        DefaultTableModel model = (DefaultTableModel) TabelDosenKelasAnda.getModel();
        model.addRow(new Object[]{NID, Nama, Kode, Gender, Topik, Email});
    }
    
    public void setTabelMhsKelasIkut(String NIM, String Nama){
        DefaultTableModel model = (DefaultTableModel) TabelMhsIkut.getModel();
        model.addRow(new Object[]{NIM, Nama});
    }
    
    public void setTabelDosenKelasIkut(String NID, String Nama){
        DefaultTableModel model = (DefaultTableModel) TabelDosenIkut.getModel();
        model.addRow(new Object[]{NID, Nama});
    }
    
    public JList getListIkutKelas(){
        return ListIkutLihatKelas;
    }
    
    public int getIndexListIkutKelas(){
        return ListIkutLihatKelas.getSelectedIndex();
    }
    
    public void setListIkutKelas(String[] s){
        ListIkutLihatKelas.setListData(s);
    }
    //End of Lihat Kelas

    //Ubah Password
    public JButton getbtnUbahPass(){
        return btnUbahPass;
    }
    
    public String getPasswordLama(){
        return tfPasswordLama.getText();
    }
    
    public String getPasswordBaru(){
        return tfPasswordBaru.getText();
    }
    
    public String getKonfirmPassword(){
        return tfKonfirmPassword.getText();
    }
    //End of Ubah Password
    
    //Konfirmasi
    public void setTabelKonfirmasi(String NIM, String Nama, String Gender, String Email, String Topik){
        DefaultTableModel model = (DefaultTableModel) TabelKonfirmasi.getModel();
        model.addRow(new Object[]{NIM, Nama, Gender, Email, Topik});
    }
    
    public int getIndexKonfirmasi(){
        return TabelKonfirmasi.getSelectedRow();
    }
    
    public JButton getbtnTerimaKonfirmasi(){
        return btnTerimaKonfirmasi;
    }
    
    public JButton getbtnTolakKonfirmasi(){
        return btnTolakKonfirmasi;
    }
    //End of Konfirmasi
    
    public JButton getbtnHapusKelasTA(){
        return btnHapusKelasTA;
    }
    
    public JButton getbtnLogOut(){
        return btnLogOut;
    }
    
    public void setTextNamaDosen(String s){
        TextNamaDosen.setText(s);
    }
    
    public void setTextNIDDosen(String s){
        TextNIDDosen.setText(s);
    }
    
    public void addActionListener(ActionListener a1) {
        btnLogOut.addActionListener(a1);
        btnHapusMhs.addActionListener(a1);
        btnUbahPass.addActionListener(a1);
        btnBuatKelas.addActionListener(a1);
        btnHapusDosen.addActionListener(a1);
        btnTambahDosen.addActionListener(a1);
        btnHapusKelasTA.addActionListener(a1);
        btnTolakKonfirmasi.addActionListener(a1);
        btnTerimaKonfirmasi.addActionListener(a1);
    }
    
    public void addMouseAdapter(MouseAdapter ma) {
        ListIkutLihatKelas.addMouseListener(ma);
        ListKelasBuatTA.addMouseListener(ma);
        TabelTambahDosen.addMouseListener(ma);
        TabelHapusDosen.addMouseListener(ma);
        TabelHapusMhs.addMouseListener(ma);
        TabelKonfirmasi.addMouseListener(ma);
    }
    
    public void ResetView(){
        DefaultTableModel model = (DefaultTableModel) TabelDosenBuatKelas.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) TabelMhsBuatKelas.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) TabelMhsKelasAnda.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) TabelDosenKelasAnda.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) TabelHapusDosen.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) TabelHapusMhs.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) TabelTambahDosen.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) TabelMhsIkut.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) TabelDosenIkut.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) TabelKonfirmasi.getModel();
        model.setRowCount(0);
        
        
        TabelMhsKelasAnda.clearSelection();
        TabelMhsBuatKelas.clearSelection();
        TabelDosenKelasAnda.clearSelection();
        TabelMhsKelasAnda.clearSelection();
        TabelTambahDosen.clearSelection();
        TabelHapusDosen.clearSelection();
        TabelHapusMhs.clearSelection();
        TabelKonfirmasi.clearSelection();
        TabelDosenIkut.clearSelection();
        TabelMhsIkut.clearSelection();
        tfPasswordBaru.setText("");
        tfPasswordLama.setText("");
        tfKonfirmPassword.setText("");
        
    }
}
