/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muhith
 */
public class MahasiswaMenu extends javax.swing.JFrame {

   
    public MahasiswaMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel4 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnBuatTA = new javax.swing.JButton();
        btnUbahPassword = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnRegisTA = new javax.swing.JButton();
        btnUbahTA = new javax.swing.JButton();
        btnDeleteTA = new javax.swing.JButton();
        ParentPanel = new javax.swing.JPanel();
        PanelHOME = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        textNamaNIM = new javax.swing.JLabel();
        PanelUbahPassword = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfPasswordLamaDiUbahPassword = new javax.swing.JPasswordField();
        tfPasswordBaruDiUbahPassword = new javax.swing.JPasswordField();
        tfConfirmPasswordDiUbahPassword = new javax.swing.JPasswordField();
        btnUbahDiMenuPassword = new javax.swing.JButton();
        PanelBuatTA = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfJudulTAdiBuatTA = new javax.swing.JTextField();
        btnBuatDiMenuBuatTA = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        tfJudulTAAndaDiBuatTA = new javax.swing.JTextField();
        PanelUbahTA = new javax.swing.JPanel();
        PanelHomeUbahTA = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfUbahJudulTA = new javax.swing.JTextField();
        btnUbahTADiMenuUbahTA = new javax.swing.JButton();
        PanelDeleteTA = new javax.swing.JPanel();
        PanelHomeHapusTA = new javax.swing.JPanel();
        btnHapusTADiMenuHapusTA = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfJudulTADiHapusTA = new javax.swing.JTextField();
        PanelRegisTA = new javax.swing.JPanel();
        PanelHomeRegisTA = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listKelasTADiRegistrasiTA = new javax.swing.JList<>();
        btnDaftarDiMenuRegistrasiTA = new javax.swing.JButton();
        btnAjukanPembimbingDiRegistrasiTA = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        btnLihatDataKelasTADiRegistrasiTA = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelDosenRegistrasi = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TabelMhsRegistrasi = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        PanelAjukanPembimbingRegisTA = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TabelDosenKelasTA = new javax.swing.JTable();
        btnAjukanPembimbing = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ListPengajuan = new javax.swing.JList<>();
        btnKembaliDiAjukanPembimbing = new javax.swing.JButton();
        PanelLihatDataKelasTA = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        TabelMhsKelasAnda = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        TabelDosenKelasAnda = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnKembaliDiLihatDataKelasTA = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        TabelPembimbing = new javax.swing.JTable();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(51, 0, 0));

        btnHome.setBackground(new java.awt.Color(102, 0, 0));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("HOME");
        btnHome.setFocusPainted(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_1rsz_1200px-telkom_university_logosvg.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("S");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("I");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("S");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("F");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("O");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("A");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("T");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        btnBuatTA.setBackground(new java.awt.Color(102, 0, 0));
        btnBuatTA.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnBuatTA.setForeground(new java.awt.Color(255, 255, 255));
        btnBuatTA.setText("Buat TA");
        btnBuatTA.setFocusPainted(false);
        btnBuatTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatTAActionPerformed(evt);
            }
        });

        btnUbahPassword.setBackground(new java.awt.Color(102, 0, 0));
        btnUbahPassword.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnUbahPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahPassword.setText("Ubah password");
        btnUbahPassword.setFocusPainted(false);
        btnUbahPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahPasswordActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(102, 0, 0));
        btnLogout.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setFocusPainted(false);

        btnRegisTA.setBackground(new java.awt.Color(102, 0, 0));
        btnRegisTA.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnRegisTA.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisTA.setText("Registrasi Kelas TA");
        btnRegisTA.setFocusPainted(false);
        btnRegisTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisTAActionPerformed(evt);
            }
        });

        btnUbahTA.setBackground(new java.awt.Color(102, 0, 0));
        btnUbahTA.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnUbahTA.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahTA.setText("Ubah TA");
        btnUbahTA.setFocusPainted(false);
        btnUbahTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahTAActionPerformed(evt);
            }
        });

        btnDeleteTA.setBackground(new java.awt.Color(102, 0, 0));
        btnDeleteTA.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnDeleteTA.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteTA.setText("Hapus TA");
        btnDeleteTA.setFocusPainted(false);
        btnDeleteTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUbahPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuatTA, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUbahTA, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteTA, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnRegisTA, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbahPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuatTA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisTA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbahTA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteTA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        ParentPanel.setBackground(new java.awt.Color(204, 204, 255));
        ParentPanel.setLayout(new java.awt.CardLayout());

        PanelHOME.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELAMAT DATANG DI SISTEM INFORMASI");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("TUGAS AKHIR");

        textNamaNIM.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textNamaNIM.setForeground(new java.awt.Color(51, 0, 0));
        textNamaNIM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelHOMELayout = new javax.swing.GroupLayout(PanelHOME);
        PanelHOME.setLayout(PanelHOMELayout);
        PanelHOMELayout.setHorizontalGroup(
            PanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHOMELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHOMELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textNamaNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        PanelHOMELayout.setVerticalGroup(
            PanelHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHOMELayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(59, 59, 59)
                .addComponent(textNamaNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        ParentPanel.add(PanelHOME, "card2");

        PanelUbahPassword.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENU UBAH PASSWORD");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("Password Lama");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("Password Baru");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("Confirm Password");

        tfPasswordLamaDiUbahPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfPasswordLamaDiUbahPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordLamaDiUbahPasswordActionPerformed(evt);
            }
        });

        tfPasswordBaruDiUbahPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tfConfirmPasswordDiUbahPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnUbahDiMenuPassword.setBackground(new java.awt.Color(0, 102, 0));
        btnUbahDiMenuPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUbahDiMenuPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahDiMenuPassword.setText("Ubah Password");

        javax.swing.GroupLayout PanelUbahPasswordLayout = new javax.swing.GroupLayout(PanelUbahPassword);
        PanelUbahPassword.setLayout(PanelUbahPasswordLayout);
        PanelUbahPasswordLayout.setHorizontalGroup(
            PanelUbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUbahPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelUbahPasswordLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(PanelUbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUbahDiMenuPassword)
                    .addGroup(PanelUbahPasswordLayout.createSequentialGroup()
                        .addGroup(PanelUbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(80, 80, 80)
                        .addGroup(PanelUbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfConfirmPasswordDiUbahPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addComponent(tfPasswordBaruDiUbahPassword)
                            .addComponent(tfPasswordLamaDiUbahPassword))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelUbahPasswordLayout.setVerticalGroup(
            PanelUbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUbahPasswordLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(PanelUbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfPasswordLamaDiUbahPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PanelUbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfPasswordBaruDiUbahPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(PanelUbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfConfirmPasswordDiUbahPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(btnUbahDiMenuPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        ParentPanel.add(PanelUbahPassword, "card3");

        PanelBuatTA.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MENU BUAT TUGAS AKHIR");

        tfJudulTAdiBuatTA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnBuatDiMenuBuatTA.setBackground(new java.awt.Color(0, 102, 0));
        btnBuatDiMenuBuatTA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuatDiMenuBuatTA.setForeground(new java.awt.Color(255, 255, 255));
        btnBuatDiMenuBuatTA.setText("Buat");
        btnBuatDiMenuBuatTA.setFocusPainted(false);

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(51, 0, 0));
        jLabel46.setText("Judul TA");

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 0, 0));
        jLabel47.setText("Judul TA Anda");

        tfJudulTAAndaDiBuatTA.setEditable(false);
        tfJudulTAAndaDiBuatTA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout PanelBuatTALayout = new javax.swing.GroupLayout(PanelBuatTA);
        PanelBuatTA.setLayout(PanelBuatTALayout);
        PanelBuatTALayout.setHorizontalGroup(
            PanelBuatTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuatTALayout.createSequentialGroup()
                .addGroup(PanelBuatTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBuatTALayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE))
                    .addGroup(PanelBuatTALayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(PanelBuatTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelBuatTALayout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addGap(118, 118, 118)
                                .addComponent(tfJudulTAdiBuatTA, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelBuatTALayout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addGap(118, 118, 118)
                                .addGroup(PanelBuatTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuatDiMenuBuatTA, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfJudulTAAndaDiBuatTA, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelBuatTALayout.setVerticalGroup(
            PanelBuatTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuatTALayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addGap(113, 113, 113)
                .addGroup(PanelBuatTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(tfJudulTAdiBuatTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnBuatDiMenuBuatTA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(PanelBuatTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(tfJudulTAAndaDiBuatTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );

        ParentPanel.add(PanelBuatTA, "card4");

        PanelUbahTA.setBackground(new java.awt.Color(204, 204, 204));
        PanelUbahTA.setLayout(new java.awt.CardLayout());

        PanelHomeUbahTA.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MENU UBAH TUGAS AKHIR");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 0));
        jLabel13.setText("Ubah Judul");

        tfUbahJudulTA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnUbahTADiMenuUbahTA.setBackground(new java.awt.Color(0, 102, 0));
        btnUbahTADiMenuUbahTA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUbahTADiMenuUbahTA.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahTADiMenuUbahTA.setText("Ubah TA");

        javax.swing.GroupLayout PanelHomeUbahTALayout = new javax.swing.GroupLayout(PanelHomeUbahTA);
        PanelHomeUbahTA.setLayout(PanelHomeUbahTALayout);
        PanelHomeUbahTALayout.setHorizontalGroup(
            PanelHomeUbahTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHomeUbahTALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHomeUbahTALayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(tfUbahJudulTA, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
            .addGroup(PanelHomeUbahTALayout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(btnUbahTADiMenuUbahTA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelHomeUbahTALayout.setVerticalGroup(
            PanelHomeUbahTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHomeUbahTALayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addGap(107, 107, 107)
                .addGroup(PanelHomeUbahTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUbahJudulTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(66, 66, 66)
                .addComponent(btnUbahTADiMenuUbahTA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        PanelUbahTA.add(PanelHomeUbahTA, "card15");

        ParentPanel.add(PanelUbahTA, "card5");

        PanelDeleteTA.setBackground(new java.awt.Color(204, 204, 204));

        PanelHomeHapusTA.setBackground(new java.awt.Color(204, 204, 204));

        btnHapusTADiMenuHapusTA.setBackground(new java.awt.Color(0, 102, 0));
        btnHapusTADiMenuHapusTA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHapusTADiMenuHapusTA.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusTADiMenuHapusTA.setText("Hapus TA");

        jLabel23.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("MENU HAPUS TUGAS AKHIR");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 0));
        jLabel14.setText("Judul TA");

        tfJudulTADiHapusTA.setEditable(false);
        tfJudulTADiHapusTA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfJudulTADiHapusTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJudulTADiHapusTAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelHomeHapusTALayout = new javax.swing.GroupLayout(PanelHomeHapusTA);
        PanelHomeHapusTA.setLayout(PanelHomeHapusTALayout);
        PanelHomeHapusTALayout.setHorizontalGroup(
            PanelHomeHapusTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHomeHapusTALayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelHomeHapusTALayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(PanelHomeHapusTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapusTADiMenuHapusTA, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJudulTADiHapusTA, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelHomeHapusTALayout.setVerticalGroup(
            PanelHomeHapusTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHomeHapusTALayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(PanelHomeHapusTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfJudulTADiHapusTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnHapusTADiMenuHapusTA)
                .addGap(146, 146, 146))
        );

        javax.swing.GroupLayout PanelDeleteTALayout = new javax.swing.GroupLayout(PanelDeleteTA);
        PanelDeleteTA.setLayout(PanelDeleteTALayout);
        PanelDeleteTALayout.setHorizontalGroup(
            PanelDeleteTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHomeHapusTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PanelDeleteTALayout.setVerticalGroup(
            PanelDeleteTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHomeHapusTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ParentPanel.add(PanelDeleteTA, "card6");

        PanelRegisTA.setBackground(new java.awt.Color(204, 204, 204));
        PanelRegisTA.setLayout(new java.awt.CardLayout());

        PanelHomeRegisTA.setBackground(new java.awt.Color(204, 204, 204));

        jLabel28.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 0, 0));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("MENU REGISTRASI TUGAS AKHIR");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 0, 0));
        jLabel29.setText("List Kelas TA ");

        listKelasTADiRegistrasiTA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(listKelasTADiRegistrasiTA);

        btnDaftarDiMenuRegistrasiTA.setBackground(new java.awt.Color(0, 102, 0));
        btnDaftarDiMenuRegistrasiTA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDaftarDiMenuRegistrasiTA.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftarDiMenuRegistrasiTA.setText("Daftar");
        btnDaftarDiMenuRegistrasiTA.setFocusPainted(false);

        btnAjukanPembimbingDiRegistrasiTA.setBackground(new java.awt.Color(0, 102, 0));
        btnAjukanPembimbingDiRegistrasiTA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAjukanPembimbingDiRegistrasiTA.setForeground(new java.awt.Color(255, 255, 255));
        btnAjukanPembimbingDiRegistrasiTA.setText("Ajukan Pembimbing");
        btnAjukanPembimbingDiRegistrasiTA.setFocusPainted(false);
        btnAjukanPembimbingDiRegistrasiTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjukanPembimbingDiRegistrasiTAActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 0, 0));
        jLabel37.setText("Jika anda sudah memiliki kelas");

        jLabel38.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 0, 0));
        jLabel38.setText("TA :");

        btnLihatDataKelasTADiRegistrasiTA.setBackground(new java.awt.Color(0, 102, 0));
        btnLihatDataKelasTADiRegistrasiTA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLihatDataKelasTADiRegistrasiTA.setForeground(new java.awt.Color(255, 255, 255));
        btnLihatDataKelasTADiRegistrasiTA.setText("Lihat Data Kelas TA");
        btnLihatDataKelasTADiRegistrasiTA.setFocusPainted(false);
        btnLihatDataKelasTADiRegistrasiTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatDataKelasTADiRegistrasiTAActionPerformed(evt);
            }
        });

        TabelDosenRegistrasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NID", "Nama"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelDosenRegistrasi);

        TabelMhsRegistrasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TabelMhsRegistrasi);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Data Dosen");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 0, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Data Mahasiswa");

        javax.swing.GroupLayout PanelHomeRegisTALayout = new javax.swing.GroupLayout(PanelHomeRegisTA);
        PanelHomeRegisTA.setLayout(PanelHomeRegisTALayout);
        PanelHomeRegisTALayout.setHorizontalGroup(
            PanelHomeRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHomeRegisTALayout.createSequentialGroup()
                .addGroup(PanelHomeRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelHomeRegisTALayout.createSequentialGroup()
                        .addGroup(PanelHomeRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelHomeRegisTALayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHomeRegisTALayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel29)
                                .addGap(78, 78, 78)))
                        .addGroup(PanelHomeRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelHomeRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelHomeRegisTALayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(PanelHomeRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addComponent(btnDaftarDiMenuRegistrasiTA, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38)
                                    .addComponent(btnAjukanPembimbingDiRegistrasiTA, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLihatDataKelasTADiRegistrasiTA, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addGroup(PanelHomeRegisTALayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelHomeRegisTALayout.setVerticalGroup(
            PanelHomeRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHomeRegisTALayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel28)
                .addGap(55, 55, 55)
                .addGroup(PanelHomeRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(PanelHomeRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelHomeRegisTALayout.createSequentialGroup()
                        .addComponent(btnDaftarDiMenuRegistrasiTA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAjukanPembimbingDiRegistrasiTA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLihatDataKelasTADiRegistrasiTA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );

        PanelRegisTA.add(PanelHomeRegisTA, "card2");

        PanelAjukanPembimbingRegisTA.setBackground(new java.awt.Color(204, 204, 204));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 0, 0));
        jLabel39.setText("Data dosen kelas TA anda :");

        TabelDosenKelasTA.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        TabelDosenKelasTA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NID", "Nama", "Kode Dosen", "Gender", "Topik", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(TabelDosenKelasTA);

        btnAjukanPembimbing.setBackground(new java.awt.Color(0, 102, 0));
        btnAjukanPembimbing.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAjukanPembimbing.setForeground(new java.awt.Color(255, 255, 255));
        btnAjukanPembimbing.setText("Ajukan pembimbing");
        btnAjukanPembimbing.setFocusPainted(false);
        btnAjukanPembimbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjukanPembimbingActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 0, 0));
        jLabel40.setText("List Pengajuan :");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("*Mahasiswa hanya dapat memiliki 2 dosen pembimbing");

        ListPengajuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane6.setViewportView(ListPengajuan);

        btnKembaliDiAjukanPembimbing.setBackground(new java.awt.Color(0, 102, 0));
        btnKembaliDiAjukanPembimbing.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnKembaliDiAjukanPembimbing.setForeground(new java.awt.Color(255, 255, 255));
        btnKembaliDiAjukanPembimbing.setText("Kembali");
        btnKembaliDiAjukanPembimbing.setFocusPainted(false);
        btnKembaliDiAjukanPembimbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliDiAjukanPembimbingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAjukanPembimbingRegisTALayout = new javax.swing.GroupLayout(PanelAjukanPembimbingRegisTA);
        PanelAjukanPembimbingRegisTA.setLayout(PanelAjukanPembimbingRegisTALayout);
        PanelAjukanPembimbingRegisTALayout.setHorizontalGroup(
            PanelAjukanPembimbingRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAjukanPembimbingRegisTALayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelAjukanPembimbingRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addGroup(PanelAjukanPembimbingRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAjukanPembimbingRegisTALayout.createSequentialGroup()
                        .addGroup(PanelAjukanPembimbingRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5)
                            .addGroup(PanelAjukanPembimbingRegisTALayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAjukanPembimbing)))
                        .addGap(143, 143, 143))
                    .addGroup(PanelAjukanPembimbingRegisTALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembaliDiAjukanPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        PanelAjukanPembimbingRegisTALayout.setVerticalGroup(
            PanelAjukanPembimbingRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAjukanPembimbingRegisTALayout.createSequentialGroup()
                .addGroup(PanelAjukanPembimbingRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelAjukanPembimbingRegisTALayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembaliDiAjukanPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAjukanPembimbingRegisTALayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(PanelAjukanPembimbingRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))
                        .addGap(18, 18, 18)
                        .addGroup(PanelAjukanPembimbingRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAjukanPembimbing)
                            .addComponent(jLabel41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelAjukanPembimbingRegisTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40))
                        .addGap(38, 38, 38)))
                .addGap(61, 61, 61))
        );

        PanelRegisTA.add(PanelAjukanPembimbingRegisTA, "card4");

        PanelLihatDataKelasTA.setBackground(new java.awt.Color(204, 204, 204));

        TabelMhsKelasAnda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabelMhsKelasAnda.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        TabelMhsKelasAnda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Gender", "Email", "Judul"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(TabelMhsKelasAnda);

        TabelDosenKelasAnda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabelDosenKelasAnda.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        TabelDosenKelasAnda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NID", "Nama", "Kode Dosen", "Gender", "Topik", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(TabelDosenKelasAnda);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 0));
        jLabel7.setText("Data Mahasiswa Dikelas TA anda");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 0));
        jLabel12.setText("Data Dosen Dikelas TA anda");

        btnKembaliDiLihatDataKelasTA.setBackground(new java.awt.Color(0, 102, 0));
        btnKembaliDiLihatDataKelasTA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnKembaliDiLihatDataKelasTA.setForeground(new java.awt.Color(255, 255, 255));
        btnKembaliDiLihatDataKelasTA.setText("Kembali");
        btnKembaliDiLihatDataKelasTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliDiLihatDataKelasTAActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 0));
        jLabel10.setText("Pembimbing Tugas Akhir Anda : ");

        TabelPembimbing.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabelPembimbing.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        TabelPembimbing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Kode Dosen", "NID", "Gender", "Email", "Topik"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(TabelPembimbing);

        javax.swing.GroupLayout PanelLihatDataKelasTALayout = new javax.swing.GroupLayout(PanelLihatDataKelasTA);
        PanelLihatDataKelasTA.setLayout(PanelLihatDataKelasTALayout);
        PanelLihatDataKelasTALayout.setHorizontalGroup(
            PanelLihatDataKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLihatDataKelasTALayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(138, 138, 138))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLihatDataKelasTALayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelLihatDataKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelLihatDataKelasTALayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLihatDataKelasTALayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembaliDiLihatDataKelasTA, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        PanelLihatDataKelasTALayout.setVerticalGroup(
            PanelLihatDataKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLihatDataKelasTALayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(PanelLihatDataKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLihatDataKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(PanelLihatDataKelasTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLihatDataKelasTALayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(11, 11, 11)
                        .addComponent(btnKembaliDiLihatDataKelasTA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        PanelRegisTA.add(PanelLihatDataKelasTA, "card5");

        ParentPanel.add(PanelRegisTA, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuatTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatTAActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(PanelBuatTA);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_btnBuatTAActionPerformed

    private void btnUbahPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahPasswordActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(PanelUbahPassword);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_btnUbahPasswordActionPerformed

    private void btnUbahTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahTAActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(PanelUbahTA);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_btnUbahTAActionPerformed

    private void btnDeleteTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTAActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(PanelDeleteTA);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_btnDeleteTAActionPerformed

    private void btnRegisTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisTAActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(PanelRegisTA);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_btnRegisTAActionPerformed

    private void btnKembaliDiAjukanPembimbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliDiAjukanPembimbingActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(PanelRegisTA);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_btnKembaliDiAjukanPembimbingActionPerformed

    private void btnAjukanPembimbingDiRegistrasiTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjukanPembimbingDiRegistrasiTAActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(PanelAjukanPembimbingRegisTA);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_btnAjukanPembimbingDiRegistrasiTAActionPerformed

    private void tfJudulTADiHapusTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJudulTADiHapusTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJudulTADiHapusTAActionPerformed

    private void btnLihatDataKelasTADiRegistrasiTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatDataKelasTADiRegistrasiTAActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(PanelLihatDataKelasTA);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_btnLihatDataKelasTADiRegistrasiTAActionPerformed

    private void btnKembaliDiLihatDataKelasTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliDiLihatDataKelasTAActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(PanelRegisTA);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_btnKembaliDiLihatDataKelasTAActionPerformed

    private void tfPasswordLamaDiUbahPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordLamaDiUbahPasswordActionPerformed
        
    }//GEN-LAST:event_tfPasswordLamaDiUbahPasswordActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        ParentPanel.removeAll();
        ParentPanel.add(PanelHOME);
        ParentPanel.repaint();
        ParentPanel.revalidate();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAjukanPembimbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjukanPembimbingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjukanPembimbingActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListPengajuan;
    private javax.swing.JPanel PanelAjukanPembimbingRegisTA;
    private javax.swing.JPanel PanelBuatTA;
    private javax.swing.JPanel PanelDeleteTA;
    private javax.swing.JPanel PanelHOME;
    private javax.swing.JPanel PanelHomeHapusTA;
    private javax.swing.JPanel PanelHomeRegisTA;
    private javax.swing.JPanel PanelHomeUbahTA;
    private javax.swing.JPanel PanelLihatDataKelasTA;
    private javax.swing.JPanel PanelRegisTA;
    private javax.swing.JPanel PanelUbahPassword;
    private javax.swing.JPanel PanelUbahTA;
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JTable TabelDosenKelasAnda;
    private javax.swing.JTable TabelDosenKelasTA;
    private javax.swing.JTable TabelDosenRegistrasi;
    private javax.swing.JTable TabelMhsKelasAnda;
    private javax.swing.JTable TabelMhsRegistrasi;
    private javax.swing.JTable TabelPembimbing;
    private javax.swing.JButton btnAjukanPembimbing;
    private javax.swing.JButton btnAjukanPembimbingDiRegistrasiTA;
    private javax.swing.JButton btnBuatDiMenuBuatTA;
    private javax.swing.JButton btnBuatTA;
    private javax.swing.JButton btnDaftarDiMenuRegistrasiTA;
    private javax.swing.JButton btnDeleteTA;
    private javax.swing.JButton btnHapusTADiMenuHapusTA;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnKembaliDiAjukanPembimbing;
    private javax.swing.JButton btnKembaliDiLihatDataKelasTA;
    private javax.swing.JButton btnLihatDataKelasTADiRegistrasiTA;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegisTA;
    private javax.swing.JButton btnUbahDiMenuPassword;
    private javax.swing.JButton btnUbahPassword;
    private javax.swing.JButton btnUbahTA;
    private javax.swing.JButton btnUbahTADiMenuUbahTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList<String> listKelasTADiRegistrasiTA;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JLabel textNamaNIM;
    private javax.swing.JPasswordField tfConfirmPasswordDiUbahPassword;
    private javax.swing.JTextField tfJudulTAAndaDiBuatTA;
    private javax.swing.JTextField tfJudulTADiHapusTA;
    private javax.swing.JTextField tfJudulTAdiBuatTA;
    private javax.swing.JPasswordField tfPasswordBaruDiUbahPassword;
    private javax.swing.JPasswordField tfPasswordLamaDiUbahPassword;
    private javax.swing.JTextField tfUbahJudulTA;
    // End of variables declaration//GEN-END:variables

    
    //Ubah Password
    public String getTfConfirmPassword() {
        return tfConfirmPasswordDiUbahPassword.getText();
    }

    public String getTfPasswordBaru() {
        return tfPasswordBaruDiUbahPassword.getText();
    }

    public String getTfPasswordLama() {
        return tfPasswordLamaDiUbahPassword.getText();
    }
    //end of Ubah Password
    
    
    //Buat TA
    public String getTfJudulTAdiBuatTA(){
        return tfJudulTAdiBuatTA.getText();
    }
    
    public String getTfJudulTAAndaDiBuatTA(){
        return tfJudulTAAndaDiBuatTA.getText();
    }
    
    public void setTfJudulTAAndaDiBuatTA(String Judul){
        tfJudulTAAndaDiBuatTA.setText(Judul);
    }
    //end of Buat TA
    
    
    //Ubah TA
    public String getTfUbahJudulTA() {
        return tfUbahJudulTA.getText();
    }
    public void setUbahJudulTA(String Judul){
        tfUbahJudulTA.setText(Judul);
    }
    //end of Ubah TA
    
    
    //Hapus TA
    public String getTfJudulTADiHapusTA(){
        return tfJudulTADiHapusTA.getText();
    }
    
    public void setTfJudulTADiHapusTA(String Judul){
        tfJudulTADiHapusTA.setText(Judul);
    }
     //End of Hapus TA
    
    
    //Daftar Registrasi Kelas TA
    public JButton getbtnRegisTA(){
        return btnRegisTA;
    }
    
    public JButton getbtnDaftarKelasTA(){
        return btnDaftarDiMenuRegistrasiTA;
    }
    
    public JList getListRegistrasiKelasTA(){
        return listKelasTADiRegistrasiTA;
    }
    
    public int getIndexListRegistrasiKelasTA(){
        return listKelasTADiRegistrasiTA.getSelectedIndex();
    }
    
    public void setListRegistrasiKelasTA(String[] s){
        listKelasTADiRegistrasiTA.setListData(s);
    }
    
    public void setTabelMhsRegistrasi(String NIM, String Nama){
        DefaultTableModel model = (DefaultTableModel) TabelMhsRegistrasi.getModel();
        model.addRow(new Object[]{NIM, Nama});
    }
    
    public void setTabelDosenRegistrasi(String NID, String Nama){
        DefaultTableModel model = (DefaultTableModel) TabelDosenRegistrasi.getModel();
        model.addRow(new Object[]{NID, Nama});
    }
    //End of Daftar Registrasi Kelas TA

    //Daftar Dosen Pembimbing
    public JButton getbtnDaftarPembimbing(){
        return btnAjukanPembimbing;
    }
    
    public int getSelectedRowPembimbing(){
        return TabelDosenKelasTA.getSelectedRow();
    }
    
    public void setTabelDosenPembimbing(String NID, String Nama, String Kode, String Gender, String Topik, String Email){
        DefaultTableModel model = (DefaultTableModel) TabelDosenKelasTA.getModel();
        model.addRow(new Object[]{NID, Nama, Kode, Gender, Topik, Email});
    }
    
    public void setQuePembimbing(String[] s){
        ListPengajuan.setListData(s);
    }
    
    public int getIndexQuePembimbing(){
        return ListPengajuan.getSelectedIndex();
    }
    
    //End of Daftar Dosen Pembimbing
    
    //Lihat Kelas TA
    public void setTabelDosenKelas(String NID, String Nama, String Kode, String Gender, String Topik, String Email){
        DefaultTableModel model = (DefaultTableModel) TabelDosenKelasAnda.getModel();
        model.addRow(new Object[]{NID, Nama, Kode, Gender, Topik, Email});
    }
    
    public void setTabelMhsKelas(String NIM, String Nama, String Gender, String Email, String Topik){
        DefaultTableModel model = (DefaultTableModel) TabelMhsKelasAnda.getModel();
        model.addRow(new Object[]{NIM, Nama, Gender, Email, Topik});
    }
    
    public void setTabelPembimbing(String NID, String Nama, String Kode, String Gender, String Topik, String Email){
        DefaultTableModel model = (DefaultTableModel) TabelPembimbing.getModel();
        model.addRow(new Object[]{NID, Nama, Kode, Gender, Topik, Email});
    }
    //End of Lihat Kelas TA
    
    public void addActionListener(ActionListener al){
        btnLogout.addActionListener(al);
        btnUbahDiMenuPassword.addActionListener(al);
        btnBuatDiMenuBuatTA.addActionListener(al);
        btnUbahTADiMenuUbahTA.addActionListener(al);
        btnDaftarDiMenuRegistrasiTA.addActionListener(al);
        btnAjukanPembimbing.addActionListener(al);
        btnHapusTADiMenuHapusTA.addActionListener(al);
        btnDeleteTA.addActionListener(al);
        btnRegisTA.addActionListener(al);
    }
    
    public void addMouseAdapter(MouseAdapter ma){
        listKelasTADiRegistrasiTA.addMouseListener(ma);
        ListPengajuan.addMouseListener(ma);
        
    }

    public void setTextNamaNIM(String s){
        textNamaNIM.setText(s);
    }
    
    public JButton getBtnLogout() {
        return btnLogout;
    }
    
    public JButton getBtnUbahTADiMenuUbahTA(){
        return btnUbahTADiMenuUbahTA;
    }

    public JButton getBtnUbahDiMenuPassword() {
        return btnUbahDiMenuPassword;
    }
    
    public JButton getBtnBuatDiMenuBuatTA(){
        return btnBuatDiMenuBuatTA;
    }
    
    public JButton getBtnHapusTADiMenuHapusTA(){
        return btnHapusTADiMenuHapusTA;    
    }
    public JButton getBtnDeleteTA(){
        return btnDeleteTA;
    }
    
    public void resetView(){
        DefaultTableModel model = (DefaultTableModel) TabelMhsRegistrasi.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) TabelDosenRegistrasi.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) TabelMhsKelasAnda.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) TabelDosenKelasAnda.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) TabelPembimbing.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) TabelDosenKelasTA.getModel();
        model.setRowCount(0);
        
        TabelMhsRegistrasi.clearSelection();
        TabelDosenRegistrasi.clearSelection();
        TabelMhsKelasAnda.clearSelection();
        TabelDosenKelasAnda.clearSelection();
        TabelPembimbing.clearSelection();
        TabelDosenKelasTA.clearSelection();
        
        tfPasswordLamaDiUbahPassword.setText("");
        tfPasswordBaruDiUbahPassword.setText("");
        tfConfirmPasswordDiUbahPassword.setText("");
        tfJudulTAdiBuatTA.setText("");
    }
}
